# Generated by Django 4.1.1 on 2022-09-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='address',
            new_name='skills',
        ),
    ]
