# Generated by Django 4.1.1 on 2022-09-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_learner_options_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='address',
            new_name='interested_subjects',
        ),
        migrations.RenameField(
            model_name='learner',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='interested_categories',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='mobile_no',
        ),
    ]
