# Generated by Django 4.1.1 on 2022-09-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chapter_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
