# Generated by Django 4.1.1 on 2022-10-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_course_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
