# Generated by Django 4.1.1 on 2022-10-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_learnercourseenrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learner'),
        ),
    ]
